name: flutter_icons
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
  - assets/image/logo.png

msix_config:
  display_name: IconSearch
  publisher_display_name: Inforgra
  identity_name: icon_search.ja.inforgra.com
  msix_version: 1.0.0.0